<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DefineConstants>Release</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
	<None Remove="Pages\ChartModule\ChartComponent.razor.css" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="Syncfusion.Blazor.Charts" Version="*" />
	  <PackageReference Include="Syncfusion.Blazor.Buttons" Version="*" />
	  <PackageReference Include="Syncfusion.Blazor.Layouts" Version="*" />
	  <PackageReference Include="Syncfusion.Blazor.Lists" Version="*" />
	  <PackageReference Include="Syncfusion.Blazor.Navigations" Version="*" />
	  <PackageReference Include="Syncfusion.Blazor.CircularGauge" Version="*" />
	  <PackageReference Include="Syncfusion.Blazor.Inputs" Version="*" />
	  <PackageReference Include="Syncfusion.Blazor.Popups" Version="*" />
	  <PackageReference Include="Syncfusion.Blazor.StockChart" Version="*" />
	  <PackageReference Include="Syncfusion.Blazor.Grid" Version="*" />
	  <PackageReference Include="Syncfusion.Blazor.Themes" Version="*" />
  </ItemGroup>

</Project>
